export const ActionTypes = {
    APPLICATION_CART_INCREMENT: "APPLICATION_CART_INCREMENT",
    APPLICATION_CART_DECREMENT: "APPLICATION_CART_DECREMENT",
    APPLICATION_CART_CLEAR: "APPLICATION_CART_CLEAR",
}